# Site settings
title: DongwooKim
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dongwoo-kim9.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dongwookim
user_description: Studying Coding, ME
user_title: ME
email: stmick9535@gmail.com
#twitter_username: https://www.instagram.com/east_woo02/
github_username:  dongwoo-kim9
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
